### ISSUE TITLE
Couldn't install tgstat  on windows

### ISSUE THREAD

**Issue by zyb1984** [tanaylab/tgstat#5]
Couldn't install tgstat  on windows, also try to install  tgstat with source like this "install.packages("tgstat",type="source")" , do you have a plan to develop a tgstat version with compatibility on windows

**Comment by aviezerl** [comment]
`tgstat` relies heavily on the Unix forking mechanism for parallelization, and therefore we currently do not have a plan to develop a windows compatible version. 

In any case, if your Windows version supports it, you can try install `tgstat` on WSL.
